[package]
name = "bevy_inochi2d"
version = "0.1.1"
edition = "2024"
description = "Renderizador independiente de Inochi2D impulsado por el backend wgpu de Bevy"
repository = "https://github.com/Huskysis/bevy_inochi2d"
license = "MIT OR Apache-2.0"
authors = ["Huskysis"]
keywords = ["bevy", "inochi2d", "rendering", "2d", "puppet"]
categories = ["rendering", "game-development", "graphics"]
exclude = ["assets/", "examples/"]

[dependencies]
inochi2d-parser = { version = "0.1" }
thiserror = { version = "2", default-features = false }
bytemuck = { version = "1.14", features = ["derive"] }


[dependencies.bevy]
version = "0.17"
default-features = false
features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite_render",
    "bevy_sprite",
    "bevy_asset",
]

[dependencies.bevy_image]
version = "0.17"
default-features = false
features = ["png", "tga"]


[dev-dependencies]
bevy = "0.17"
